### PR TITLE
logging: redirect ERROR messages to stderr (to pass back to the proxy)

### PR DESCRIPTION
**Pull request by xginn8**
Change-type: patch
Signed-off-by: Matthew McGinn <matthew@balena.io>

### CODE REVIEW

**Comment by xginn8** [comment]
this change is a small nicety that i noticed while debugging something else entirely.

before: 
resinhup-no-stderr

after:
resinhup-with-stderr

**Comment by xginn8** [comment]
It should be part of coreutils, @agherzan do you mean generally across OS
versions or specifically before calling the binary?

**Comment by agherzan** [comment]
We introduce a tool dependency on the OS. How do we maintain that? We can't assume any dependency - not even coreutils. This is a question for @imrehg too.

**Comment by xginn8** [comment]
@agherzan since this is provided as part of a busybox applet, i see [the common core busybox config](https://github.com/balena-os/meta-balena/blob/ce3efa3a66b91522d8beec6a4d9eb76c5b73a5e6/meta-balena-common/recipes-core/busybox/busybox/defconfig#L294) contains the requisite config. I also see [rocko](https://github.com/balena-os/meta-balena/blob/609118963ab642a858469202d36538a7978fa1b2/meta-resin-rocko/recipes-core/busybox/busybox/defconfig#L294) and [pyro](https://github.com/balena-os/meta-balena/blob/609118963ab642a858469202d36538a7978fa1b2/meta-resin-pyro/recipes-core/busybox/busybox/defconfig#L294) having this config variable defined, do you have a way of tracking what depends on these various busybox configuration flags?

**Comment by agherzan** [comment]
That's the food for thought here. We don't have a way now to express this dependency.

**Pull request merged**
